spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seek
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        batch_size: 30
        order_inserts: true
  security:
    user:
      name: user  # Usuario por defecto
      password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  config:
    properties:
      business:
        average-life-expectancy: 80
      user:
        auth:
          username: roberto
          password: $2a$10$GY1CSo8yQm2DmonvQwrpMet99AEd9bW/NMD2cbhxxPHs3CJukMZum
          role: ADMIN
server:
  port: 9090
jwt:
  secret:
    key: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  time:
    expiration: 3600000
logging:
  file:
    name: /home/usrfc/mth-applications/biller/log/seek-customer.log
  level:
    root: INFO
    org:
      springframework: ERROR
      hibernate: ERROR
      springframework.boot.web.embedded.tomcat: INFO
    com:
      seek:
        rbenitez:
          customer: DEBUG
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"